server:
  port: '9999'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customerservice
          uri: lb://customerservice
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: payservice
          uri: lb://payservice
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=2
        - id: reservationservice
          uri: lb://reservationservice
          predicates:
            - Path=/api/reservation/**
          filters:
            - StripPrefix=2
        - id: stationservice
          uri: lb://stationservice
          predicates:
            - Path=/api/station/**
          filters:
            - StripPrefix=2