server:
  port: '9999'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=2
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/api/pays/**
          filters:
            - StripPrefix=2
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
          filters:
            - StripPrefix=2
        - id: station-service
          uri: lb://station-service
          predicates:
            - Path=/api/stations/**
          filters:
            - StripPrefix=2