server:
  port: '9999'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customerservice
          uri: lb://customerservice
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=2
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservation/**
          filters:
            - StripPrefix=2
        - id: station-service
          uri: lb://station-service
          predicates:
            - Path=/api/station/**
          filters:
            - StripPrefix=2